name: Relyance SCI Scan
on:
  schedule:
    - cron: "50 5 * * 0"
  workflow_dispatch:
jobs:
  execute-relyance-sci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run SCI
        run: |-
          docker pull gcr.io/relyance-ext/compliance_inspector_eu1:release &&           docker run --rm -v $(pwd):/repo --env "API_KEY=${{ secrets.RELYANCE_API_KEY }}"           gcr.io/relyance-ext/compliance_inspector_eu1:release
